version: 2

workflows:
  version: 2
  default:
    jobs:
    - build

jobs:
  build:
    working_directory: "/docker/project"
    docker:
    - image: blockmason/java:11.0.1
    steps:
    - checkout
    - run:
        name: Building
        command: ./gradlew build
    - run:
        name: Archiving
        command: ./gradlew jar
    - run:
        name: Generating documentation
        command: ./gradlew javadoc
